### ISSUE TITLE
配置了mint  铭刻次数就会出错

### ISSUE THREAD

**Issue by bluestar2021** [bitxx/evm-inscriptions#4]
New client config object fail: error converting YAML to JSON: yaml: invalid trailing UTF-8 octet, use default param to start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58354a]

goroutine 1 [running]:
github.com/bitxx/logger/logbase.(*Helper).Errorf(0x0, {0x878185, 0x2d}, {0xc00010e680, 0x1, 0x1})
        /Users/ld/Documents/project/go/pkg/mod/github.com/bitxx/logger@v1.6.2/logbase/helper.go:80 +0x4a
evm-inscriptions/utils/log.Errorf(...)
        /Users/ld/Desktop/evm-inscriptions/utils/log/log.go:73
main.main.func1()
        /Users/ld/Desktop/evm-inscriptions/main.go:31 +0x85
main.main()
        /Users/ld/Desktop/evm-inscriptions/main.go:50 +0x48f

**Comment by bitxx** [comment]
> New client config object fail: error converting YAML to JSON: yaml: invalid trailing UTF-8 octet, use default param to start panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58354a]
> 
> goroutine 1 [running]: github.com/bitxx/logger/logbase.(*Helper).Errorf(0x0, {0x878185, 0x2d}, {0xc00010e680, 0x1, 0x1}) /Users/ld/Documents/project/go/pkg/mod/github.com/bitxx/logger@v1.6.2/logbase/helper.go:80 +0x4a evm-inscriptions/utils/log.Errorf(...) /Users/ld/Desktop/evm-inscriptions/utils/log/log.go:73 main.main.func1() /Users/ld/Desktop/evm-inscriptions/main.go:31 +0x85 main.main() /Users/ld/Desktop/evm-inscriptions/main.go:50 +0x48f

这个显示你的某个配置参数格式有问题，可否脱敏后贴出配置来具体看看怎么一回事

**Comment by bluestar2021** [comment]
![111111111111111](https://github.com/bitxx/evm-inscriptions/assets/83041424/53495bef-096c-4a6d-9383-920a1a155a38)

**Comment by bluestar2021** [comment]
![Uploading 111111111111111.png…]()

**Comment by bluestar2021** [comment]
![123](https://github.com/bitxx/evm-inscriptions/assets/83041424/92c4331e-89d9-4d11-8233-4b267f80f090)

**Comment by bluestar2021** [comment]
> 这个显示你的某个配置参数格式有问题，可否脱敏后贴出配置来具体看看怎么一回事

大佬 有空看下怎么回事吗
